### PR TITLE
added docker support

### PR DESCRIPTION
**Pull request by keydon**
if you want to provide a pre-built image
via docker-hub, change the compose file
accordingly.

### CODE REVIEW

**Comment by ciphax** [comment]
Hi,
adding docker support is a good idea but there are some issues with your current implementation:
- There is no way to issue more than one certificate
- There is no way to renew a certificate
- Your image acts like a 'one-shot' container but leaves behind a full letsencrypt folder volume

I think a better solution would be to support the creation of multiple certificates and to include a crontab daemon that automatically calls `certbot renew` once per day so you just have to keep the container running.

**Comment by keydon** [comment]
well i see your points. for now all i needed was a new single wildcard certificate for my domains, so yes i guess my scope was a little narrow and i probably will improve it a little once mine need renewal.

but still, the CMD instruction is completly overrideable (in commandline or docker-compose.yml) without touching the Dockerfile
/Image. So ppl can still do whatever certbot can do. meaning they could use it for regular renewal. i guess most work is needed for documentation and some examples on how to use it.

**Comment by ciphax** [comment]
Sorry for the late response. Yes you're right but I think at least some more documentation is necessary to merge.

**Comment by ciphax** [comment]
A modified version of your pull request is now merged. It now uses a multistage docker build to create a small image which is based on the official certbot image (which uses alpine). I did also add some documentation and change the entrypoint script a bit.
Thanks for contributing 🙂

**Pull request merged**
